name: Deploy Vue App with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Add this step to install Node.js and npm
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify the Node.js version you need
      
      # Add this step to install your project dependencies
      - name: Install dependencies
        run: npm install
      
      # Modify this step to build your Vue.js app
      - name: Build Vue.js App
        run: npm run build
        # Assuming your Vue.js project is in a subdirectory named 'vueapp' and outputs to 'dist'
        working-directory: ./vueapp
      
      # Add a step to copy the Vue.js build output to the Jekyll destination folder
      - name: Copy Vue.js build to Jekyll
        run: cp -r ./vueapp/dist/* ./_site
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
